using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ConsoleApplication1
{
    public enum CitiesEnum
    {
        Acre,
        Afula,
        Arad,
        Ariel,
        Ashdod,
        Ashkelon,
        BatYam,
        Beersheba,
        BeitShean,
        BeitShemesh,
        BeitarIllit,
        BneiBrak,
        Dimona,
        Eilat,
        Elad,
        GivatShmuel,
        Givatayim,
        Hadera,
        Haifa,
        Herzliya,
        HodHaSharon,
        Holon,
        Jerusalem,
        Karmiel,
        KiryatAta,
        KiryatBialik,
        KiryatGat,
        KiryatMalakhi,
        KiryatMotzkin,
        KiryatOno,
        KiryatShmona,
        KiryatYam,
        KfarSaba,
        Lod,
        MaaleAdumim,
        MaalotTarshiha,
        MigdalHaEmek,
        ModiinMaccabimReut,
        ModiinIllit,
        Nahariya,
        NazarethIllit,
        Nesher,
        NessZiona,
        Netanya,
        Netivot,
        Ofakim,
        OrAkiva,
        OrYehuda,
        PetahTikva,
        Raanana,
        RamatGan,
        RamatHaSharon,
        Ramla,
        Rehovot,
        RishonLeZion,
        RoshHaAyin,
        Safed,
        Sderot,
        TelAvivYaffo,
        Tiberias,
        TiratCarmel,
        Yavne,
        YehudMonosson,
        Yokneam
    }
}
